//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexMarkup.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexMarkup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examinar....
        /// </summary>
        internal static string configRegexMarkup_buttonExaminar {
            get {
                return ResourceManager.GetString("configRegexMarkup_buttonExaminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string configRegexMarkup_buttonSave {
            get {
                return ResourceManager.GetString("configRegexMarkup_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string configRegexMarkup_enUS {
            get {
                return ResourceManager.GetString("configRegexMarkup_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string configRegexMarkup_esES {
            get {
                return ResourceManager.GetString("configRegexMarkup_esES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar archivo externo.
        /// </summary>
        internal static string configRegexMarkup_labelExternalFile {
            get {
                return ResourceManager.GetString("configRegexMarkup_labelExternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string configRegexMarkup_language {
            get {
                return ResourceManager.GetString("configRegexMarkup_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuratión RegexMarkup.
        /// </summary>
        internal static string configRegexMarkup_title {
            get {
                return ResourceManager.GetString("configRegexMarkup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No esta definido issn.
        /// </summary>
        internal static string RegexMarkup_issnNotDefined {
            get {
                return ResourceManager.GetString("RegexMarkup_issnNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la cita(s) completamente.
        /// </summary>
        internal static string RegexMarkup_selectCitationComplete {
            get {
                return ResourceManager.GetString("RegexMarkup_selectCitationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se econtro la revista en el archivo xml.
        /// </summary>
        internal static string RegexMarkup_serilaNotInXML {
            get {
                return ResourceManager.GetString("RegexMarkup_serilaNotInXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegexMarkup.
        /// </summary>
        internal static string RegexMarkup_title {
            get {
                return ResourceManager.GetString("RegexMarkup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string RibbonRegexMarkup_buttonConfiguration {
            get {
                return ResourceManager.GetString("RibbonRegexMarkup_buttonConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string ValidateMarkup_buttonEnd {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera.
        /// </summary>
        internal static string ValidateMarkup_buttonFirst {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última.
        /// </summary>
        internal static string ValidateMarkup_buttonLast {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string ValidateMarkup_buttonNext {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string ValidateMarkup_buttonPrev {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita {0} de {1}.
        /// </summary>
        internal static string ValidateMarkup_citationOf {
            get {
                return ResourceManager.GetString("ValidateMarkup_citationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita marcada:.
        /// </summary>
        internal static string ValidateMarkup_labelmarkup {
            get {
                return ResourceManager.GetString("ValidateMarkup_labelmarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita original:.
        /// </summary>
        internal static string ValidateMarkup_labelOriginal {
            get {
                return ResourceManager.GetString("ValidateMarkup_labelOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string ValidateMarkup_radioButtonNo {
            get {
                return ResourceManager.GetString("ValidateMarkup_radioButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string ValidateMarkup_radioButtonYes {
            get {
                return ResourceManager.GetString("ValidateMarkup_radioButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación y marcación de las citas.
        /// </summary>
        internal static string ValidateMarkup_title {
            get {
                return ResourceManager.GetString("ValidateMarkup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere por favor.
        /// </summary>
        internal static string Waiting_labelWait {
            get {
                return ResourceManager.GetString("Waiting_labelWait", resourceCulture);
            }
        }
    }
}
