//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexMarkup.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexMarkup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examinar....
        /// </summary>
        internal static string configRegexMarkup_buttonExaminar {
            get {
                return ResourceManager.GetString("configRegexMarkup_buttonExaminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string configRegexMarkup_buttonSave {
            get {
                return ResourceManager.GetString("configRegexMarkup_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string configRegexMarkup_enUS {
            get {
                return ResourceManager.GetString("configRegexMarkup_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string configRegexMarkup_esES {
            get {
                return ResourceManager.GetString("configRegexMarkup_esES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar archivo externo.
        /// </summary>
        internal static string configRegexMarkup_labelExternalFile {
            get {
                return ResourceManager.GetString("configRegexMarkup_labelExternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string configRegexMarkup_language {
            get {
                return ResourceManager.GetString("configRegexMarkup_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuratión RegexMarkup.
        /// </summary>
        internal static string configRegexMarkup_title {
            get {
                return ResourceManager.GetString("configRegexMarkup_title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string EditAttribute_buttonCancel {
            get {
                return ResourceManager.GetString("EditAttribute_buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string EditAttribute_buttonEdit {
            get {
                return ResourceManager.GetString("EditAttribute_buttonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de atributos.
        /// </summary>
        internal static string EditAttribute_title {
            get {
                return ResourceManager.GetString("EditAttribute_title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap first {
            get {
                object obj = ResourceManager.GetObject("first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap last {
            get {
                object obj = ResourceManager.GetObject("last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prev {
            get {
                object obj = ResourceManager.GetObject("prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No esta definido issn.
        /// </summary>
        internal static string RegexMarkup_issnNotDefined {
            get {
                return ResourceManager.GetString("RegexMarkup_issnNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la cita(s) completamente.
        /// </summary>
        internal static string RegexMarkup_selectCitationComplete {
            get {
                return ResourceManager.GetString("RegexMarkup_selectCitationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se econtro la revista en el archivo xml.
        /// </summary>
        internal static string RegexMarkup_serilaNotInXML {
            get {
                return ResourceManager.GetString("RegexMarkup_serilaNotInXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegexMarkup.
        /// </summary>
        internal static string RegexMarkup_title {
            get {
                return ResourceManager.GetString("RegexMarkup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string RibbonRegexMarkup_buttonConfiguration {
            get {
                return ResourceManager.GetString("RibbonRegexMarkup_buttonConfiguration", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upArrow {
            get {
                object obj = ResourceManager.GetObject("upArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ValidateMarkup_buttonCancelToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonCancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elimina la etiqueta seleccionada.
        /// </summary>
        internal static string ValidateMarkup_buttonClearTagToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonClearTagToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar atributos de la etiqueta seleccionada.
        /// </summary>
        internal static string ValidateMarkup_buttonEditAttrToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonEditAttrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar las citas marcadas.
        /// </summary>
        internal static string ValidateMarkup_buttonEndToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonEndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la primer cita.
        /// </summary>
        internal static string ValidateMarkup_buttonFirstToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonFirstToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la última.
        /// </summary>
        internal static string ValidateMarkup_buttonLastToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonLastToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la siguiente cita.
        /// </summary>
        internal static string ValidateMarkup_buttonNextToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonNextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la cita anterior.
        /// </summary>
        internal static string ValidateMarkup_buttonPrevToolTip {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonPrevToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rehacer.
        /// </summary>
        internal static string ValidateMarkup_buttonRedo {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshacer.
        /// </summary>
        internal static string ValidateMarkup_buttonUndo {
            get {
                return ResourceManager.GetString("ValidateMarkup_buttonUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodos dentro de la etiqueta {0}.
        /// </summary>
        internal static string ValidateMarkup_childTags {
            get {
                return ResourceManager.GetString("ValidateMarkup_childTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} de {1}.
        /// </summary>
        internal static string ValidateMarkup_citationOf {
            get {
                return ResourceManager.GetString("ValidateMarkup_citationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando etiqueta .
        /// </summary>
        internal static string ValidateMarkup_deleteTagCaption {
            get {
                return ResourceManager.GetString("ValidateMarkup_deleteTagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro de eliminar la etiqueta &quot;{0}&quot;?.
        /// </summary>
        internal static string ValidateMarkup_deleteTagMessage {
            get {
                return ResourceManager.GetString("ValidateMarkup_deleteTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita marcada:.
        /// </summary>
        internal static string ValidateMarkup_groupBoxMarkup {
            get {
                return ResourceManager.GetString("ValidateMarkup_groupBoxMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita original:.
        /// </summary>
        internal static string ValidateMarkup_groupBoxOriginal {
            get {
                return ResourceManager.GetString("ValidateMarkup_groupBoxOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas.
        /// </summary>
        internal static string ValidateMarkup_groupBoxTools {
            get {
                return ResourceManager.GetString("ValidateMarkup_groupBoxTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar cita.
        /// </summary>
        internal static string ValidateMarkup_labelCitationStatus {
            get {
                return ResourceManager.GetString("ValidateMarkup_labelCitationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La seleccion no corresponde a una etiqueta.
        /// </summary>
        internal static string ValidateMarkup_messageNoTagSelection {
            get {
                return ResourceManager.GetString("ValidateMarkup_messageNoTagSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La etiqueta seleccionada no contiene atributos.
        /// </summary>
        internal static string ValidateMarkup_messageTagWithoutAttr {
            get {
                return ResourceManager.GetString("ValidateMarkup_messageTagWithoutAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar al nivel superior {0}.
        /// </summary>
        internal static string ValidateMarkup_parentTag {
            get {
                return ResourceManager.GetString("ValidateMarkup_parentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string ValidateMarkup_radioButtonNo {
            get {
                return ResourceManager.GetString("ValidateMarkup_radioButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string ValidateMarkup_radioButtonYes {
            get {
                return ResourceManager.GetString("ValidateMarkup_radioButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación y marcación de las citas.
        /// </summary>
        internal static string ValidateMarkup_title {
            get {
                return ResourceManager.GetString("ValidateMarkup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere por favor.
        /// </summary>
        internal static string Waiting_labelWait {
            get {
                return ResourceManager.GetString("Waiting_labelWait", resourceCulture);
            }
        }
    }
}
